language: php

php:
  - 5.6
  - 7.3

branches:
  only:
    - develop
    - master

before_script:
  - travis_retry composer install --no-interaction --prefer-source
  - cd tests

script:
  - vendor/bin/phpunit -c phpunit-travis.xml